server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/bt_forum?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    org.butu: debug
