server:
  port: 8000

web:
  domain: http://localhost

#数据库配置
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/bt_forum?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

  #Knife4J运行依赖
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#是否激活 swagger
swagger:
  enable: true

#日志配置
logging:
  level:
    root: info
    org.butu: debug

#JWT配置
jwt:
  # Bearer Token
  tokenHead: 'Bearer '
  # Authorization
  tokenHeader: 'Authorization'
  # Token失效时间 :60*60*24*7
  expiration: 604800
  # 私钥
  secret: '2CF24FE663DBB493E56BA4E31BE6FD03'

#七牛云配置
oss:
  domain: http://r8uj7z8yq.hd-bkt.clouddn.com/     # 访问域名(默认使用七牛云测试域名)
  accessKey: vzzbIV5XEzTXF-sQMjXRxX9NvBuHBGy3B9hVWJ9S # 公钥
  secretKey: 5cjcnrzrDxX2bHTdZ90fJyUwJcM13HPfNyB5dd1w # 私钥
  bucket: butu  #存储空间名称

#安全路径白名单
secure:
  ignored:
    urls:
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /user/register
      - /user/login
      - /user/info
      - /user/logout
      - /user/active
      - /tip/today
      - /post/list
      - /promotion/all
      - /billboard/show
      - /billboard/count
      - /comment/get_comments
      - /user/verify
      - /user/token
      - /upload
      - /doc.html
      - /swagger-resources/**
      - /swagger/**

