server:
  port: 8000

web:
  domain: http://localhost

#数据库配置
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/bt_forum?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

#发送邮件
  mail:
    #这个需要根据你开启的服务的邮箱是QQ邮箱,还是网易邮箱区分
    #smtp.163.com为网易邮箱,smtp.qq.com为QQ邮箱
    host: smtp.qq.com
    username: 1781894948@qq.com #你开通SMTP服务的邮箱账号
    password: xeqzstieuetlecfd #刚刚生成的授权码,不是邮箱密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  #Knife4J运行依赖
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#是否激活 swagger
swagger:
  enable: true

#日志配置
logging:
  level:
    root: info
    org.butu: debug

#JWT配置
jwt:
  # Bearer Token
  tokenHead: 'Bearer '
  # Authorization
  tokenHeader: 'Authorization'
  # Token失效时间 :60*60*24*7
  expiration: 604800
  # 私钥
  secret: '2CF24FE663DBB493E56BA4E31BE6FD03'

#七牛云配置
oss:
  domain: http://rb3enpa19.hn-bkt.clouddn.com/     # 访问域名(默认使用七牛云测试域名)
  accessKey: vzzbIV5XEzTXF-sQMjXRxX9NvBuHBGy3B9hVWJ9S # 公钥
  secretKey: 5cjcnrzrDxX2bHTdZ90fJyUwJcM13HPfNyB5dd1w # 私钥
  bucket: butu2  #存储空间名称

#安全路径白名单
secure:
  ignored:
    urls:
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /user/register
      - /user/login
      - /user/info
      - /user/logout
      - /user/active
      - /tip/today
      - /post/list
      - /promotion/all
      - /promotion/list
      - /billboard/show
      - /billboard/count
      - /comment/get_comments
      - /user/verify
      - /user/token
      - /upload
      - /doc.html
      - /swagger-resources/**
      - /swagger/**
      - /carousel/show
      - /user/findMail
      - /user/getMailUser
      - /user/resetPwd
      - /api/pushMessage/**
      - /pushToWeb
      - /tag/recommendTags

#  #邮件发送
#  spring.mail.host=smtp.qq.com
#  spring.mail.default-encoding=UTF-8
#  # 发送账号，用户名，也就是使用哪个邮箱发送
#  spring.mail.username=1781894948@qq.com
#  # 密码，这里密码一般指的是授权密码，开启POP3/SMTP服务
#  spring.mail.password=xeqzstieuetlecfd
#  # 邮箱验证链接前缀，到时候拼接uuid
#  my-config-mail.ip=http://127.0.0.1:8088/verifyMail/

