server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/bt_forum?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    org.butu: debug

jwt:
  # Bearer Token
  tokenHead: 'Bearer '
  # Authorization
  tokenHeader: 'Authorization'
  # Token失效时间 :60*60*24*7
  expiration: 604800
  # 私钥
  secret: '2CF24FE663DBB493E56BA4E31BE6FD03'

secure:
  ignored:
    urls: #安全路径白名单
      - /tip/today
      - /user/login
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /user/register
      - /user/login
      - /user/info
      - /logout
      - /user/active
      - /post/list
      - /tip/today
      - /promotion/all
